name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: packages/lit-frontend

      - name: Build frontend
        run: npm run build
        working-directory: packages/lit-frontend

      - name: Upload frontend to S3
        run: |
          aws s3 sync packages/lit-frontend/dist s3://foodbracket-frontend --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Install backend dependencies
        run: npm install
        working-directory: packages/express-backend

      - name: Build backend
        run: npm run build
        working-directory: packages/express-backend

      - name: Deploy backend to Elastic Beanstalk
        run: |
          zip -r backend.zip .
          aws elasticbeanstalk create-application-version --application-name foodbracket-backend --version-label latest --source-bundle S3Bucket=foodbracket-frontend,S3Key=backend.zip
          aws elasticbeanstalk update-environment --application-name foodbracket-backend --environment-name foodbracket-backend-env --version-label latest
        working-directory: packages/express-backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
