name: Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1
      VERSION_LABEL: v${{ github.run_number }}-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
        working-directory: packages/lit-frontend

      - name: Build frontend
        run: npm run build
        working-directory: packages/lit-frontend

      - name: Upload frontend to S3
        run: |
          aws s3 sync packages/lit-frontend/dist s3://foodbracket-frontend --delete --region ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install backend dependencies
        run: npm install
        working-directory: packages/express-backend

      - name: Build backend
        run: npm run build
        working-directory: packages/express-backend

      - name: Zip backend
        run: |
          cd packages/express-backend
          zip -r backend.zip dist node_modules package.json .ebextensions Procfile
          mv backend.zip ../../
        working-directory: .

      - name: Upload backend zip to S3
        run: |
          aws s3 cp backend.zip s3://foodbracket-backend/backend.zip --region ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy backend to Elastic Beanstalk
        run: |
          VERSION_LABEL=$(date +%Y%m%d%H%M%S)
          aws elasticbeanstalk create-application-version --application-name foodbracket-backend --version-label $VERSION_LABEL --source-bundle S3Bucket=foodbracket-backend,S3Key=backend.zip --region ${{ env.AWS_REGION }}
          aws elasticbeanstalk update-environment --application-name foodbracket-backend --environment-name Foodbracket-backend-env --version-label $VERSION_LABEL --region ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*" --region ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
